services:
  mysql:
    # latest = 8.4.0
    image: mysql
    # container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: ravil
      MYSQL_PASSWORD: R1b2I34
      MYSQL_ROOT_PASSWORD: R1b2I34
    volumes:
      - ./.server/db/:/var/lib/mysql

  wp:
    # latest = 6.5.3-php8.2-apache
    image: wordpress
    # container_name: wp
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ravil
      WORDPRESS_DB_PASSWORD: R1b2I34
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    ports:
      - 8000:80
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./.server/wp/:/var/www/html
      - ./.server/custom.php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./theme/:/var/www/html/wp-content/themes/example
      - ./plugin/:/var/www/html/wp-content/plugins/example
    
  pma:
    # latest = 5.2.1-apache
    image: phpmyadmin
    # container_name: pma
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    depends_on:
      - mysql

  mailhog:
    # latest = v1.0.1
    image: mailhog/mailhog
    # container_name: mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
